#int SCOPE_SYSTEM = 0
#int SCOPE_TASK   = 1
#int SCOPE_AGENT  = 2

#string INTERRUPT_PAUSE  = 'pause'
#string INTERRUPT_RESUME = 'unpause'
#string INTERRUPT_RESET  = 'reset'

#string INTERRUPT_TOC_PAUSE  = 'toc_pause'
#string INTERRUPT_TOC_RESUME = 'toc_unpause'
#string INTERRUPT_TOC_RESET  = 'toc_cancel'

#string INTERRUPT_FORCE_RESET  = 'force_cancel_task'
#string INTERRUPT_DELETE_AGENT  = 'delete_agent'

string interrupt
string scope
string target

